### PR TITLE
Sex check v1.1.0 dev

### PR DESCRIPTION
**Pull request by pofuoku**
Changes made:

- Utilized normalised score to infer sex.
- Refactored code to adhere to Pylint syntax standards.
- Added a test directory to repo

Example job: https://platform.dnanexus.com/panx/projects/Ggp655Q4Zpk9XYP55qQFQZZF/monitor/job/GjF56xj4ZpkJzqPPjp2XKk9Q

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @pofuoku)

___
*[`dxapp.json` line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB7or122yhERrxQJ5L:-NvB7or2-Kwy2A_Wbkcr:b-22kgzm) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/dxapp.json#L7)):*
> ```JSON
>   "dxapi": "1.0.0",
>   "version": "1.1.0",
>   "whatsNew": "Uses normalised reads count (score) to infer sex",
> ```

Could you include details of the version plus the change in this field, like this:
https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/2cccf624e825cc9da4ee3ccbd23dd9040832fa74/dxapp.json#L7

So that over time we accumulate a description of what was added in each version



_Code quote:_
```JSON
 "whatsNew": "Uses normalised reads count (score) to infer sex",
```
___
*[`README.md` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB8JoG3n5Xrza4POGJ:-NvB8JoG3n5Xrza4POGK:b-bkfxb1) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/README.md#L25)):*
> ```Markdown
> 2. A corresponding index file (.bai),
> 3. Male threshold (float) - A threshold for determining male based on chromosome Y reads.
> 4. Female threshold (float) - A threshold for determining female based on chromosome Y reads.
> ```

Could you elaborate slightly on how the threshold is used? 
i.e.
is a sample male if it's above or below the male threshold?
is a sample female if it's above or below the female threshold?



_Code quote:_
```Markdown
3. Male threshold (float) - A threshold for determining male based on chromosome Y reads.
4. Female threshold (float) - A threshold for determining female based on chromosome Y reads.
```
___
*[`src/sex_check.py` line 56 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB9By86pQiHLd1JssV:-NvB9By86pQiHLd1JssW:b-ph7hws) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L56)):*
> ```Python
>     with open(filename, encoding="utf-8") as file:
>         for line in file:
>             if line.startswith("1"):
> ```

What happens here if the line contains a record for chromosome 11, 12, 13 etc? Will it (incorrectly) include them in the count?



_Code quote:_
```Python
if line.startswith("1"):
```
___
*[`src/sex_check.py` line 66 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB9rk61DH9IcsWKSoJ:-NvB9rk7-LWlPnYz2Lxg:b-mt8sz4) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L66)):*
> ```Python
>         print("No mapped reads for chromosome Y. Using 0 instead.")
> 
>     n_chr_y = chr_y / chr_1 if chr_1 != 0 else 0
> ```

Perhaps `norm_chr_y` would be a clearer variable name



_Code quote:_
```Python
n_chr_y
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @pofuoku)

___
*[`src/sex_check.py` line 101 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvBgx7_5zNdqjROzRZJ:-NvBgx7_5zNdqjROzRZK:bof5yhq) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L101)):*
> ```Python
>     """
>     Determines the predicted sex based on score and defined thresholds.
>     N/B: Higher score = fewer reads
> ```

Q1: fewer reads on Y, or in general?

Q2: If on Y, does a high score mean a higher a lower number of reads on Y, or does it mean a lower proportion of reads on Y? 
(i.e. would 2 samples with the same Y read count have the different scores if they have differing number of reads on chr1?)



_Code quote:_
```Python
fewer reads
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @pofuoku)

___
*[`test/test.py` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvBkTlB-mW2oS0yfUvo:-NvBkTlB-mW2oS0yfUvp:b-l04zhc) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/test/test.py#L1)):*
> ```Python
> """sex_check 1.1.0 test suite
> ```

I'll come back to this, as I think you said you're still working on it



_Code quote:_
```Python
"""sex_check 1.1.0 test suite
```

**Review by pofuoku — COMMENTED** [review]
@mattgarner 
Please see example of a completed job from last commit.
https://platform.dnanexus.com/panx/projects/Ggp655Q4Zpk9XYP55qQFQZZF/monitor/job/GjZG6fj4Zpk962QBX5Yb2Y2F

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-:-NwEGmln7hiomJRSTNSl:b-687jx6)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @mattgarner)

___
*[`src/sex_check.py` line 56 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB9By86pQiHLd1JssV:-NwEEp4J6bC3lb2G8WDl:bgqq6m4) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L56)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What happens here if the line contains a record for chromosome 11, 12, 13 etc? Will it (incorrectly) include them in the count?
</blockquote></details>

The csv library is the most robust solution I can think of; what do you make of this?
___
*[`test/test.py` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvBkTlB-mW2oS0yfUvo:-NwEGT0C5fTM_B1q31yq:bheg5cy) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/test/test.py#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I'll come back to this, as I think you said you're still working on it
</blockquote></details>

The test suite can still be improved but so far it cover most base and edge cases.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5)* status: all files reviewed, 4 unresolved discussions (waiting on @pofuoku)

___
*[`dxapp.json` line 7 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB7or122yhERrxQJ5L:-NwEOtYy6x6isAKzafOR:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/dxapp.json#L7)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could you include details of the version plus the change in this field, like this:
https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/2cccf624e825cc9da4ee3ccbd23dd9040832fa74/dxapp.json#L7

So that over time we accumulate a description of what was added in each version
</blockquote></details>

Done
___
*[`README.md` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB8JoG3n5Xrza4POGJ:-NwEOyAV6FfB5E-uqRNm:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/README.md#L25)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could you elaborate slightly on how the threshold is used? 
i.e.
is a sample male if it's above or below the male threshold?
is a sample female if it's above or below the female threshold?
</blockquote></details>

Done
___
*[`README.md` line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NwEPCsm48G8B0DEYUhP:-NwEPCsnBTc-oJjUS8aH:b-23zyy6) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/8d7415a46ea3f6dc1394354e663cc40ce8762aa1/README.md#L18)):*
> ```Markdown
> The app can be used as one of the quality control steps of sequencing data. It serves these key purposes:
> 1. Validates reported sex against genotype-inferred sex.
> 2. Detects sample swaps
> ```

Perhaps tweak the wording as suggested below (since this check detects a specific category of swaps, not all swaps)



_Suggestion:_
```Markdown
Detects male <-> female sample swaps
```
___
*[`README.md` line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NwEPUOv8Kk-386q3dKE:-NwEPUOv8Kk-386q3dKF:byzu736) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/8d7415a46ea3f6dc1394354e663cc40ce8762aa1/README.md#L20)):*
> ```Markdown
> 2. Detects sample swaps
> 3. Flags human error in data entry eg misregistration of reported sex
> 4. Detects pollution or contamination of samples, which may lead to inaccurate sex determination.
> ```

could you explain what is meant by pollution here? Is this distinct from contamination?



_Code quote:_
```Markdown
pollution or 
```
___
*[`src/sex_check.py` line 56 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB9By86pQiHLd1JssV:-NwEf0mM4Fnpr9ElmX2u:bih4mww) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L56)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

The csv library is the most robust solution I can think of; what do you make of this?
</blockquote></details>

This looks much better :+1: 
___
*[`src/sex_check.py` line 66 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvB9rk61DH9IcsWKSoJ:-NwETzkA8SHQuSBvmKXg:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L66)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps `norm_chr_y` would be a clearer variable name
</blockquote></details>

Done
___
*[`src/sex_check.py` line 101 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NvBgx7_5zNdqjROzRZJ:-NwEUCU0BKysGMXEJu3j:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/5a252b69322b067693befbd7f5237b98285cefbe/src/sex_check.py#L101)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Q1: fewer reads on Y, or in general?

Q2: If on Y, does a high score mean a higher a lower number of reads on Y, or does it mean a lower proportion of reads on Y? 
(i.e. would 2 samples with the same Y read count have the different scores if they have differing number of reads on chr1?)
</blockquote></details>

Done

**Review by pofuoku — COMMENTED** [review]
@mattgarner 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-:-NwEkWaJ76eWOWRygj2Y:bzcdi0e)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[`README.md` line 20 at r3](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NwEPUOv8Kk-386q3dKE:-NwEiicf8clIfso0PZiC:bd0hh5k) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/8d7415a46ea3f6dc1394354e663cc40ce8762aa1/README.md#L20)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

could you explain what is meant by pollution here? Is this distinct from contamination?
</blockquote></details>

It's synonymous. I've gotten rid of pollution

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pofuoku)

___
*[`README.md` line 18 at r3](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/5#-NwEPCsm48G8B0DEYUhP:-NwElIlPBqMRjgTW0UzQ:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/8d7415a46ea3f6dc1394354e663cc40ce8762aa1/README.md#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps tweak the wording as suggested below (since this check detects a specific category of swaps, not all swaps)
</blockquote></details>

Done

**Pull request merged**
