### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by pofuoku**
Example of completed job using this commit

https://platform.dnanexus.com/panx/projects/Gfx24204p0Z3Xp99bZQG94jq/monitor/job/Gfx28yj4p0Z9gV3y9VVG59vx

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)

### CODE REVIEW

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)* status: all files reviewed, 14 unresolved discussions (waiting on @pofuoku)

___
*[`dxapp.json` line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptEbSB4vfd_9QnNOgH:-NptEbSB4vfd_9QnNOgI:b-lhyhx0) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L3)):*
> ```JSON
> {
>   "name": "eggd_sex_check",
>   "title": "eggd_sex_checkv1.0.0",
> ```

the title should be eggd_sex_check, no version number needed 
___
*[`dxapp.json` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOk6W7IwohP8EKBjY:-NptOk6W7IwohP8EKBjZ:byt7njx) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L30)):*
> ```JSON
>     {
>       "name": "male_threshold",
>       "label": "Threshold for male samples",
> ```

could this label include what the threshold refers to please? i.e. that is it is number of reads mapped to Y
___
*[`dxapp.json` line 37 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOvaeBvnU65GvT-pX:-NptOvaf1JPYnkUCZiqd:bnj7hl0) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L37)):*
> ```JSON
>     {
>       "name": "female_threshold",
>       "label": "Threshold for female samples",
> ```

same as above
___
*[`dxapp.json` line 77 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOC-y9SQfl_qpGP6n:-NptOC-y9SQfl_qpGP6o:b-m3idi0) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L77)):*
> ```JSON
>           "version": "1.0.0",
>           "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>           "folder": "/app_assets/samtools/samtools_v1.18/"
> ```

samtools v1.18 is now out of date.
Could you change this so it uses the newest release please?
https://github.com/samtools/samtools/releases
___
*[`README.md` line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-Npt_dXnEB30J6ooJtde:-Npt_dXnEB30J6ooJtdf:ble2f2z) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/README.md#L12)):*
> ```Markdown
> 
> ## What does this app do?
> This app determines the sex of a sample based on mapped read counts to chromosomes Y in a given BAM file. It employs thresholds to predict the sex and compares it against the reported sex embedded in the sample name.
> ```

could you specify what the threshold refers to please? i.e. that is it is number of reads mapped to Y
___
*[`README.md` line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptPP288a_SjYr1kZwS:-NptPP288a_SjYr1kZwT:b-nfdscq) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/README.md#L16)):*
> ```Markdown
> 
> ## What are typical use cases for this app?
> It's particularly useful in quality control steps of sequencing data to confirm the reported sex against genomic data.
> ```

this is a bit unclear to me
i would get rid of "It's particularly useful" and change "against genomic data" to say something like "against the sex inferred from the genomic data"
___
*[`README.md` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptP6tDDC2YH8fKyWPf:-NptP6tDDC2YH8fKyWPg:bdshl7n) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/README.md#L23)):*
> ```Markdown
> 
> 1. A BAM file (.bam),
> 2. A corresponding index file (.bai),
> ```

this says that a .bai is required but it is an optional input in the dxapp json, could these be changed to match please (either make it required in the json or explain that it is optional in the readme)
___
*[`src/sex_check.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptLs8B10AN_sClEn_f:-NptLs8B10AN_sClEn_g:bof85n6) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L2)):*
> ```Python
> #!/usr/bin/env python
> # sex_check 0.0.1
> ```

i'd delete this comment as the version is out of date, and version info is included in the dxapp json anyway
___
*[`src/sex_check.py` line 42 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptHUcD-ajp7cN2L2Mn:-NptHUcD-ajp7cN2L2Mo:bcwl8la) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L42)):*
> ```Python
>         logging.error("An error occurred while running samtools idxstat: %s", e)
>         raise 
>     except Exception as e:
> ```

quoting Jethro here:
generally best to avoid raising a bare Exception as it can hide other bugs and make it hard to catch, a more appropriate generic error type in python to raise is a `RuntimeError`
___
*[`src/sex_check.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptI95c1tarYLi3r7Zf:-NptI95c1tarYLi3r7Zg:bcjco3r) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L75)):*
> ```Python
> 
>             if not (found_chr1 and found_chrY):
>                 raise ValueError("File does not contain required chromosome data.")
> ```

Could you include which chromosomes it's looking for i.e. 1 and Y
___
*[`src/sex_check.py` line 86 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptIm3d6P1xXFdbDAwy:-NptIm3d6P1xXFdbDAwz:b-wolpxg) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L86)):*
> ```Python
>         logging.error("Data error in file: %s", e)
>         raise
>     except Exception as e:
> ```

same as above should perhaps be a Runtime Error
___
*[`src/sex_check.py` line 114 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptK0_v5EUUsYzq25aK:-NptK0_v5EUUsYzq25aL:b-wolpxg) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L114)):*
> ```Python
>         return sex
> 
>     except Exception as e:
> ```

same as above should perhaps be a Runtime Error
___
*[`src/sex_check.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptKThu4UL32kOb_eJp:-NptKThu4UL32kOb_eJq:b8paq0n) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L169)):*
> ```Python
>     bam_file_prefix = inputs['input_bam_prefix'][0].rstrip('_markdup')
> 
>     # Fill in your application code here.
> ```

This seems left over from a template, delete.
___
*[`src/sex_check.py` line 175 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptKeky8uvLguX_Im9M:-NptKeky8uvLguX_Im9N:b-xpo6lq) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L175)):*
> ```Python
>     reported_sex = get_reported_sex(bam_file_name)
>     
>     out_file_name = bam_file_prefix + '_mcq.txt'
> ```

does mcq refer to it being used with multiqc? if so, i would change to mqc

**Review by pofuoku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)* status: 0 of 3 files reviewed, 14 unresolved discussions (waiting on @kjwinfield)

___
*[`dxapp.json` line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptEbSB4vfd_9QnNOgH:-Nq86hy53EKqQxDonIxc:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L3)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

the title should be eggd_sex_check, no version number needed
</blockquote></details>

Done.
___
*[`dxapp.json` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOk6W7IwohP8EKBjY:-Nq86nMZCqyDm-Es0w1t:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L30)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could this label include what the threshold refers to please? i.e. that is it is number of reads mapped to Y
</blockquote></details>

Done.
___
*[`dxapp.json` line 37 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOvaeBvnU65GvT-pX:-Nq86o_D6BtMw4cUf2xA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L37)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`dxapp.json` line 77 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOC-y9SQfl_qpGP6n:-Nq86rAGAnAhW4WsXun2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L77)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

samtools v1.18 is now out of date.
Could you change this so it uses the newest release please?
https://github.com/samtools/samtools/releases
</blockquote></details>

Done.
___
*[`README.md` line 12 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-Npt_dXnEB30J6ooJtde:-Nq86vl24xmKuDH2-H9J:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/README.md#L12)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could you specify what the threshold refers to please? i.e. that is it is number of reads mapped to Y
</blockquote></details>

Done.
___
*[`README.md` line 16 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptPP288a_SjYr1kZwS:-Nq86xNTA9Mkm5fqZ7E5:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/README.md#L16)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this is a bit unclear to me
i would get rid of "It's particularly useful" and change "against genomic data" to say something like "against the sex inferred from the genomic data"
</blockquote></details>

Done.
___
*[`README.md` line 23 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptP6tDDC2YH8fKyWPf:-Nq86zQB0d9YZqim93du:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/README.md#L23)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this says that a .bai is required but it is an optional input in the dxapp json, could these be changed to match please (either make it required in the json or explain that it is optional in the readme)
</blockquote></details>

Done.
___
*[`src/sex_check.py` line 2 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptLs8B10AN_sClEn_f:-Nq873xJ8U9ffKbaqecy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L2)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

i'd delete this comment as the version is out of date, and version info is included in the dxapp json anyway
</blockquote></details>

Done.
___
*[`src/sex_check.py` line 42 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptHUcD-ajp7cN2L2Mn:-Nq8Kq9sC9r2g4A6F1JA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L42)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

quoting Jethro here:
generally best to avoid raising a bare Exception as it can hide other bugs and make it hard to catch, a more appropriate generic error type in python to raise is a `RuntimeError`
</blockquote></details>

Done.
___
*[`src/sex_check.py` line 75 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptI95c1tarYLi3r7Zf:-Nq8L0oV72bmBNvHgcjG:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L75)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

Could you include which chromosomes it's looking for i.e. 1 and Y
</blockquote></details>

Done.
___
*[`src/sex_check.py` line 86 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptIm3d6P1xXFdbDAwy:-Nq8LJD0E5P6EqsmJ4Lx:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L86)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

same as above should perhaps be a Runtime Error
</blockquote></details>

Done.
___
*[`src/sex_check.py` line 114 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptK0_v5EUUsYzq25aK:-Nq8LQK22zKNKaQEl4Dm:bywvjuq) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L114)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

same as above should perhaps be a Runtime Error
</blockquote></details>

In this case, no error was raised. However, the function is intended to handle RuntimeError by logging error and returning "N" instead of terminating workflow
___
*[`src/sex_check.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptKThu4UL32kOb_eJp:-Nq8N7eMBCa-7eCUK7Wl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L169)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

This seems left over from a template, delete.
</blockquote></details>

Done.
___
*[`src/sex_check.py` line 175 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptKeky8uvLguX_Im9M:-Nq8N9ip5jBvhCuPYqYQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/src/sex_check.py#L175)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

does mcq refer to it being used with multiqc? if so, i would change to mqc
</blockquote></details>

Done.

**Comment by pofuoku** [comment]
https://platform.dnanexus.com/panx/projects/Gfx24204p0Z3Xp99bZQG94jq/monitor/job/Gg2ykpQ4p0Z5fXP19QqXq63P

Link for completed job uisng updated app

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)* status: all files reviewed, 1 unresolved discussion (waiting on @pofuoku)

___
*[`dxapp.json` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOk6W7IwohP8EKBjY:-NqCAdG30-h6x_I9mLTq:b-hr6brl) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L30)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I had another think about wording:
Because this app errors if the male threshold is less than the female, this could be made clearer by saying "Minimum number of reads mapped to Chr Y for male samples"
___
*[`dxapp.json` line 37 at r2](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NptOvaeBvnU65GvT-pX:-NqCB-cv1qiF5btpAHJf:b-xoerzs) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/981f0a3bfe34780a735d26a641b0fc0e8e0c29b6/dxapp.json#L37)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same as above, only "maximum"
___
*[`README.md` line 31 at r4](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-Nq8aqg8E9aPaIuUA8Xy:-Nq8aqg9Ds_sxqZ7Bg1X:bjbgtio) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/c0ce0f9f4c7efe90aff6bae4f5c9374ef5e39609/README.md#L31)):*
> ```Markdown
> 
> - {prefix}_idxstat.tsv: A file containing the output of samtools idxstat.
> - {prefix}_mcq.txt: A MultiQC compatible file summarising the sex check results. This file includes the sample name, mapped reads for chromosomes 1 and Y, normalized chromosome Y reads, reported sex, and predicted sex.
> ```

this is now suffixed _mqc.txt so should be updated in the readme to match

**Review by pofuoku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`README.md` line 31 at r4](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-Nq8aqg8E9aPaIuUA8Xy:-NqCEnpZ-fGgI_q1SU5_:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/c0ce0f9f4c7efe90aff6bae4f5c9374ef5e39609/README.md#L31)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this is now suffixed _mqc.txt so should be updated in the readme to match
</blockquote></details>

Done.

**Review by pofuoku — COMMENTED** [review]
Job completed using upated app

https://platform.dnanexus.com/panx/projects/Gfx24204p0Z3Xp99bZQG94jq/monitor/job/Gg2zFv04p0ZGZFz1Q51pZvJZ

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-:-NqCIOT75aklOOPGlefg:b-j828wr)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)* status: all files reviewed, 2 unresolved discussions (waiting on @pofuoku)

___
*[`dxapp.json` line 30 at r6](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NqRwEc_3Q5otSirgJGI:-NqRwEc_3Q5otSirgJGJ:b-sdr4bm) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/f148823c9c2b54c1e59057bed03b1beb5a463361/dxapp.json#L30)):*
> ```JSON
>     {
>       "name": "male_threshold",
>       "label": "Minimun number of reads mapped to Chr Y for male samples",
> ```

typo, this should read maximum
___
*[`dxapp.json` line 37 at r6](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-NqRwBaUAQOGcsZlrIqO:-NqRwBaUAQOGcsZlrIqP:bjaj3ja) ([raw file](https://github.com/eastgenomics/eggd_sex_check/blob/f148823c9c2b54c1e59057bed03b1beb5a463361/dxapp.json#L37)):*
> ```JSON
>     {
>       "name": "female_threshold",
>       "label": "Maximun for number of reads mapped to Chr Y for female samples",
> ```

typo as above

**Review by kjwinfield — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1)* status: all files reviewed, 2 unresolved discussions (waiting on @pofuoku)

**Review by kjwinfield — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_sex_check/1#-:-NqS11CY5yzlRb-j-Dbx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @pofuoku)

**Pull request merged**
